apiVersion: v1 
kind: Service 
metadata: 
  namespace: roboshop 
  name: user 
  labels:
     project: roboshop 
     component: user
     env: dev 
     tier: backend 
spec:
  selector:
    project: roboshop 
    component: user
    env: dev 
    tier: backend 
  ports:
  - protocol: TCP 
    port: 8080
    targetPort: 8080
