apiVersion: v1 
kind: Service 
metadata: 
  namespace: roboshop 
  name: cart 
  labels:
     project: roboshop 
     component: cart
     env: dev 
     tier: backend 
spec:
  selector:
    project: roboshop 
    component: cart
    env: dev 
    tier: backend 
  ports:
  - protocol: TCP 
    port: 8080
    targetPort: 8080
